### ISSUE TITLE
CMake failure

### ISSUE THREAD

**Issue by knolla** [RenderKit/superbuild#2]
Anyone ever see the following failure in a superbuild?

make VERBOSE=1 shows this:

[ 26%] Performing build step for 'rkcommon'
cd /home/knolla/intel/ms335/superbuild/build/rkcommon/build && cmake --build . --config release -j 32
Unknown argument -j
Unknown argument 32
Usage: cmake --build <dir> [options] [-- [native-options]]

This is with CMake 3.19.0-rc1 (also tried 3.16, same issue), gcc 4.8.5, GNU make 3.82.

**Comment by gregjohnson** [comment]
This type of behavior may occur if you have an older `cmake` in the environment (which doesn't support `-j`), different from the one you used to configure.

Run `which cmake` and `cmake --version` from a clean environment, and I'm guessing you'll see the older CMake there.

If so, this can be fixed by replacing any raw `cmake` calls in the superbuild with `${CMAKE_COMMAND}`.

**Comment by knolla** [comment]
Ah! Of course. I need to make sure "which cmake" finds the right cmake first. Thanks!
